### ISSUE TITLE
Differentiate between "bitfield" enums and "pure" enumeration enums

### ISSUE THREAD

**Issue by lr-evb** [ifcomp/interface-compiler#9]
Enums werden zum einen als reine Aufzählungstypen verwendet, zum anderen als Flags, die bitweise kombiniert werden können. Für letztere ist es gut und sinnvoll, dass der Interface-Compiler die in C++ nötigen Bitoperationen definiert. Für reine Aufzählungstypen sind Bitoperationen dagegen nicht sinnvoll und sogar gefährlich.

Mit diesem Ticket soll es möglich werden, im `interface.yaml` zwischen diesen beiden Einsatzzwecken zu unterscheiden und der Compiler soll eben nur noch für "Bitfield enums" die Bitoperationen generieren, für die anderen dagegen nicht mehr.

**Comment by a-krebs** [comment]
This has been implemented.
